menu:
  首页: { id: index, url: / }
  归档: { id: archives, url: /archives }
  分类: { id: categories, url: /categories }
  标签: { id: tags, url: /tags }
  阅读: { id: reading, url: /reading }
  实验室: {id: labs, url: /labs }
  关于: { id: about, url: /about }

github: gejiawen

background-root: /images/bg/
background-length: 60


avatar: /images/avatar.jpg
avatar_footer: /images/avatar_footer.gif

#### Comment
duoshuo:
  short_name: gejiawen-blog

#### tongji
baidu_tongji: true
qq_tongji: false

rss: atom.xml
