menu:
  首页: { id: index, url: / }
  归档: { id: archives, url: /archives }
  分类: { id: categories, url: /categories }
  标签: { id: tags, url: /tags }
#  阅读: { id: reading, url: /reading }
#  实验室: { id: labs, url: /labs }
  拾遗: { id: pick, url: http://book.gejiawen.com/fucking-days-to-be-a-coder, target: _blank }
  关于: { id: about, url: /about }

github: gejiawen
rss: atom.xml

search:
  id: search
  url: /search

background-root: http://7xkwt1.com1.z0.glb.clouddn.com/background-
background-length: 74

background:
  root: http://7xkwt1.com1.z0.glb.clouddn.com/background-
  length: 74
  random: false
  image: http://7xkwt1.com1.z0.glb.clouddn.com/background-64.jpg


avatar: /images/avatar.jpg


#### Comment
duoshuo:
  enable: true
  short_name: gejiawen-blog
disqus:
  enable: false
  short_name: gejiawen-blog

#### tongji
baidu_tongji: true
qq_tongji: true
google_tongji: true

#### zhanzhang
zhanzhang_baidu: true
zhanzhang_360: true

#### share
baidu_share: true
duoshuo_share: false
